name: Publish Build

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Node.js
      uses: actions/setup-node@v2

    - name: Install dependencies
      run: |
        npm install
        npm install -g vsce

    - name: Build
      run: vsce package

    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: '*.vsix'
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
